version: "3.7"
services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.6
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: 123
      # - MYSQL_ROOT_HOST=%
      # - MYSQL_ROOT_PASSWORD=123
      # - MYSQL_USER=1bd3e0294da19198
      # - MYSQL_DATABASE=1bd3e0294da19198
      # - MYSQL_PASSWORD=iAlcDxokJhGvpxaK
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      -  3306:3306 # So that you can connect to the dockerized mariadb instance from your SQL Client (i.e. HeidiSQL or PHPMyAdmin)
      
  # Enable PostgreSQL only if you use it, see development/README.md for more information.
  # postgresql:
  #   image: postgres:11.8
  #   environment:
  #     POSTGRES_PASSWORD: 123
  #   volumes:
  #     - postgresql-data:/var/lib/postgresql/data

  redis-cache:
    container_name: redis-cache
    image: redis:alpine

  redis-queue:
    container_name: redis-queue
    image: redis:alpine

  redis-socketio:
    container_name: redis-socketio
    image: redis:alpine

  frappe:
    container_name: erpnext
    image: frappe/bench:latest
    command: sleep infinity
    environment:
      - SHELL=/bin/bash
    volumes:
      - ..:/workspace:cached
      # Enable if you require git cloning
      # - ${HOME}/.ssh:/home/frappe/.ssh
    working_dir: /workspace/development
    ports:
      - 8000-8005:8000-8005
      - 9000-9005:9000-9005
    links:
      - redis-cache
      - redis-queue
      - redis-socketio
      - mariadb
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
      - redis-socketio

volumes:
  mariadb-data:
  postgresql-data:
